import NavBar from "@/components/NavBar";
import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Template from "./template";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Down The Hall",
  description: "Generated by Brendan Murphy to track readings",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full bg-background ">
        <body className={inter.className + " h-max "}>
          <div className="flex flex-col bg-background h-full">
            <NavBar />

            <Template>{children}</Template>

            <Toaster />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
